on:
- push:
  branches:
  - main
  - dev
- pull_request:
  branches:
  - main
  - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: eslint . --ext .js
